#!/bin/bash
#location of HPL 
HPL_DIR=`pwd`

# Number of CPU cores

#CPU_CORES_PER_RANK=19
CPU_CORES_PER_RANK=16
#CPU_CORES_PER_RANK=20
RANK_PER_NODE=2
echo "CPU_CORES_PER_RANK= $CPU_CORES_PER_RANK"

export OMP_NUM_THREADS=$CPU_CORES_PER_RANK
export MKL_NUM_THREADS=$CPU_CORES_PER_RANK
export LD_LIBRARY_PATH=$HPL_DIR:$LD_LIBRARY_PATH

export CUDA_DISABLE_FAST_ECC=1

export MONITOR_GPU=1
export GPU_TEMP_WARNING=75
export GPU_CLOCK_WARNING=1312
export GPU_POWER_WARNING=310
export GPU_PCIE_GEN_WARNING=3
export GPU_PCIE_WIDTH_WARNING=16

#export CUDA_DEVICE_MAX_CONNECTIONS=16
#xport TRSM_CUTOFF=16000
export TRSM_CUTOFF=1000000
#xport TRSM_CUTOFF=35000
#export GPU_DGEMM_SPLIT=1.00
export GPU_DGEMM_SPLIT=1.0
#export RANK_PERF=1100.0
#export CHECK_CPU_DGEMM_PERF=0
#export CPU_DGEMM_PERF_WARNING=1000.0

#export TEST_SYSTEM_PARAMS=0
#export TEST_LOOPS=10


#APP=$HPL_DIR/xhpl_cuda-10.0-dyn_mkl-dyn_ompi-1.10.7_gcc4.8.5_9-27-18
#APP=$HPL_DIR/xhpl_cuda-10.0-dyn_mkl-dyn_ompi-3.1.0_gcc4.8.5_9-26-18
#APP=$HPL_DIR/xhpl_cuda-10.0-dyn_mkl-static_ompi-1.10.7_gcc4.8.5_9-27-18
APP=$HPL_DIR/xhpl_cuda-10.0-dyn_mkl-static_ompi-3.1.0_gcc4.8.5_9-26-18


me=`hostname`

echo "xhpl binary= $APP"

lrank=$OMPI_COMM_WORLD_LOCAL_RANK

case ${lrank} in
0)

  ldd $APP

echo "host=$me rank= $OMPI_COMM_WORLD_RANK lrank = $lrank cores=$CPU_CORES_PER_RANK bin=$APP"
export CUDA_VISIBLE_DEVICES=0; numactl --cpunodebind=0  $APP
  ;;
1)

echo "host=$me rank= $OMPI_COMM_WORLD_RANK lrank = $lrank cores=$CPU_CORES_PER_RANK bin=$APP"
export CUDA_VISIBLE_DEVICES=4; numactl --cpunodebind=1  $APP

  ;;
esac


