#!/bin/bash
#location of HPL
HPL_DIR=`pwd`

#export PATH=/home-2/award/openmpi-1.10.2_installation_centos72_gcc485_no_cuda/bin:$PATH
#export LD_LIBRARY_PATH=/home-2/award/openmpi-1.10.2_installation_centos72_gcc485_no_cuda/lib:$LD_LIBRARY_PATH


export PATH=/home/award/openmpi-3.1.0_installation_no_cuda_no_ucx/bin:$PATH
export LD_LIBRARY_PATH=/home/award/openmpi-3.1.0_installation_no_cuda_no_ucx/lib:$LD_LIBRARY_PATH


module load cuda/10.0.130

module list

nvidia-smi

mpirun --version

#export ICHUNK_SIZE=1536
#export CHUNK_SIZE=4096
#export ICHUNK_SIZE=4096


#TEST_NAME=sl_v100x4-full-scan
#cp HPL.dat_4-gpu_full-scan-32G HPL.dat


#TEST_NAME=sl_v100x4-nb384-scan
#cp HPL.dat_4-gpu_nb384-scan-32G HPL.dat


TEST_NAME=sl_v100x4
cp HPL.dat_4-gpu-32G HPL.dat


DATETIME=`hostname`.`date +"%m%d.%H%M%S"`
mkdir ./results/HPL-$TEST_NAME-results-$DATETIME
echo "Results in folder ./results/HPL-$TEST_NAME-results-$DATETIME"
RESULT_FILE=./results/HPL-$TEST_NAME-results-$DATETIME/HPL-$TEST_NAME-results-$DATETIME-out.txt


nvidia-smi -pm 1

sudo nvidia-smi -ac 877,1230  # base clock for PCIE V100
#sudo nvidia-smi -ac 877,1290
#sudo nvidia-smi -ac 877,1380
#sudo nvidia-smi -rac

mpirun -np 4 -bind-to none  -x LD_LIBRARY_PATH ./run_linpack_GPU_sl40_4xv100_cuda10 2>&1 | tee $RESULT_FILE


# accumulated result summary
echo "RESULTS in $RESULT_FILE" >> ./results/result_summary.txt
grep "WC\|WR" $RESULT_FILE >> ./results/result_summary.txt
grep "WC\|WR" $RESULT_FILE












