#!/bin/bash
#location of HPL
HPL_DIR=`pwd`

#export PATH=/home-2/award/openmpi-1.10.2_installation_centos72_gcc485_no_cuda/bin:$PATH
#export LD_LIBRARY_PATH=/home-2/award/openmpi-1.10.2_installation_centos72_gcc485_no_cuda/lib:$LD_LIBRARY_PATH

export PATH=/home/award/openmpi-3.1.0_installation_no_cuda_no_ucx/bin:$PATH
export LD_LIBRARY_PATH=/home/award/openmpi-3.1.0_installation_no_cuda_no_ucx/lib:$LD_LIBRARY_PATH


#module load cuda/9.0.176
#module load cuda/9.1.85
module load cuda/9.2.88


module list

nvidia-smi

mpirun --version

cp HPL.dat_2x1_1_node_dgx_p100x2 HPL.dat
#cp HPL.dat_2-gpu_nb384-scan HPL.dat
#cp HPL.dat_2x1_1_node_hsw_p100x2 HPL.dat


TEST_NAME=hsw_p100x2
DATETIME=`hostname`.`date +"%m%d.%H%M%S"`
mkdir ./results/HPL-$TEST_NAME-results-$DATETIME
echo "Results in folder ./results/HPL-$TEST_NAME-results-$DATETIME"
RESULT_FILE=./results/HPL-$TEST_NAME-results-$DATETIME/HPL-$TEST_NAME-results-$DATETIME-out.txt


nvidia-smi -pm 1

#sudo nvidia-smi -ac 715,1189  # base clock for PCIE P100
sudo nvidia-smi -ac 715,1290


mpirun -np 2 -bind-to none  -x LD_LIBRARY_PATH ./run_linpack_GPU_hsw32_2xp100 2>&1 | tee $RESULT_FILE



# accumulated result summary

grep "WC\|WR" $RESULT_FILE >> ./results/result_summary.txt
grep "WC\|WR" $RESULT_FILE













